### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by hangyejiadao** [IKende/XBlog#1]
System.Net.WebException: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer [ik_max_word] not found for field [Title]"}],"type":"mapper_parsing_exception","reason":"analyzer [ik_max_word] not found for field [Title]"},"status":400} ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at BeetleX.Elasticsearch.Core.Request.OnPut(String data)
   at BeetleX.Elasticsearch.Core.Request.Execute()
   --- End of inner exception stack trace ---
   at BeetleX.Elasticsearch.Core.Request.Execute()
   at BeetleX.Elasticsearch.ESIndex.CreateType[T]()
   at BeetleX.Blog.ES.ESHelper.Init(String host) in C:\Users\Asus\Desktop\XBlog\BeetleX.Blog\ES\ESHelper.cs:line 35}

求大佬支招

**Comment by beetlex-io** [comment]
安装IK中文分词没？

**Comment by AlexYzhov** [comment]
运行elasticsearch安装目录/bin/下的elasticsearch-plugin脚本，安装ik分词插件

**Comment by colincodefirst** [comment]
No mapping found for [CreateTime] in order to sort on；


{"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [CreateTime] in order to sort on","index_uuid":"IqLCATt4Tb265rylzi6Mdw","index":"beetlex"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"beetlex","node":"Dbg8K8dbS--fgB5K4l81SA","reason":{"type":"query_shard_exception","reason":"No mapping found for [CreateTime] in order to sort on","index_uuid":"IqLCATt4Tb265rylzi6Mdw","index":"beetlex"}}]},"status":400}”

大佬求救

**Comment by wekingc** [comment]
elastic只能用6.X.X
